### ISSUE TITLE
Add a pull request for c# code changes

### ISSUE THREAD

**Issue by markcunninghamuk** [ewingjm/development-hub#25]
It would be ideal to have a smart way to detect when code changes are made. For standard customisations e.g. dynamics customisations the current process is great. The challenge is when you have C# and typescript changes, do we want to automatically merge it to master?

**Comment by ewingjm** [comment]
Making use of the full pull request functionality in Azure DevOps would be difficult as the pull requests would need to be reviewed and approved in order - unless we blocked the Development Hub while a pull request was pending (but that would then come with the disadvantage of making the merging process dependent on the extraction to source control). It'd also prevent us from making use squash merges as we'd need one commit for the source branch and one commit for the solution changes - the reason being that we absolutely don't want to move solution changes that aren't approved to the master instance, so we couldn't include them in a PR until the source branch had been approved.

The review of the source branch in the solution merge should form part of the solution merge review (as this is in effect the pull request replacement) but I appreciate this means we lose out on some of the Azure DevOps pull request functionality e.g. comment resolution, validation build. I suspect the main issue is the lack of PR validation build. 

My suggestion would be that we capture an Azure DevOps build ID on the solution records and have a Flow trigger this build on the source branch when a solution merge is created and feed that status back to the Development Hub.

**Comment by ewingjm** [comment]
It would be a lot more complicated, but there is probably a way that we could automatically create a PR when a solution merge is created with a source branch (allowing for line-by-line comments and other PR functionality) then trigger the merge process only after both the solution merge is approved _and_ all policies are resolved on the pull request. The same PR could then be updated post-merge and completed automatically. A line could be added to the PR description requesting that it not be completed as it is an automated PR.

**Comment by ewingjm** [comment]
> then trigger the merge process only after both the solution merge is approved _and_ all policies are resolved on the pull request

@markcunninghamuk @ksulikow after discussing with Kriss, we might be able to go even further than this and offer the solution extract changes with the pull request. This would involve changing the process so that there is in effect no 'Approve' or 'Reject' at the point of Solution Merge creation, but instead we do something like the following:

1. Create a solution merge as 'Queued'
2. Check if any solution merge is 'Creating pull request', 'Rejected' or 'Awaiting review' - if not, then continue to 3
3. Update status to 'Creating pull request' (for example)
3. Merge the development solution into the target environment
4. Trigger a pipeline which creates a pull request with the extracted changes (along with any code changes if a source branch is supplied)
5. On approval of the pull request, update the solution merge to 'Merged' **OR** on reject of the pull request, update the solution merge to 'Rejected'

This then results in the following scenarios:

**Merged**

If a solution merge was created after this one, start the merge process.

**Rejected**

The following buttons appear on the solution merge:
- Update - merge and push further updates with changes to the development solution
- Cancel - reset the target instance, set the solution merge to an inactive status, and start the merge process on any solution merge created after this one
